#!/usr/bin/env -S deno run -A
/**
 * build-templates.ts — テンプレートファイルをインライン化して templates.gen.ts を生成する
 *
 * JSR 経由での実行時に import.meta.dirname が undefined になる問題を回避するため、
 * テンプレートファイルの内容を TypeScript のオブジェクトとして埋め込む。
 *
 * Usage:
 *   deno run -A build-templates.ts
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

const TEMPLATE_DIR = path.resolve(import.meta.dirname!, "templates/saas-starter");
const OUTPUT_FILE = path.resolve(import.meta.dirname!, "templates.gen.ts");

// .agents/ はスキップ
const SKIP_DIRS = new Set([".agents", "node_modules", ".git"]);

interface FileEntry {
  path: string;
  content: string;
}

async function collectFiles(dir: string, base: string): Promise<FileEntry[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: FileEntry[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(base, fullPath).replace(/\\/g, "/");

    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      files.push(...await collectFiles(fullPath, base));
    } else if (entry.isFile()) {
      const content = await fs.readFile(fullPath, "utf-8");
      files.push({ path: relPath, content });
    }
  }

  return files;
}

async function main() {
  const files = await collectFiles(TEMPLATE_DIR, TEMPLATE_DIR);

  // Sort for deterministic output
  files.sort((a, b) => a.path.localeCompare(b.path));

  const lines: string[] = [
    "// AUTO-GENERATED by build-templates.ts — DO NOT EDIT",
    "// Run: deno run -A build-templates.ts",
    "//",
    `// Generated: ${new Date().toISOString()}`,
    `// Files: ${files.length}`,
    "",
    "export const TEMPLATE_FILES: ReadonlyMap<string, string> = new Map([",
  ];

  for (const file of files) {
    // Use JSON.stringify to properly escape all special characters
    const escapedPath = JSON.stringify(file.path);
    const escapedContent = JSON.stringify(file.content);
    lines.push(`  [${escapedPath}, ${escapedContent}],`);
  }

  lines.push("]);");
  lines.push("");

  await fs.writeFile(OUTPUT_FILE, lines.join("\n"));
  console.log(`✓ Generated ${OUTPUT_FILE} (${files.length} files)`);
}

main();
