// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin from "./routes/admin.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $billing from "./routes/billing.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $lp from "./routes/lp.tsx";
import * as $map_index from "./routes/map/index.tsx";
import * as $mentors_slug_ from "./routes/mentors/[slug].tsx";
import * as $mentors_index from "./routes/mentors/index.tsx";
import * as $profile_edit from "./routes/profile/edit.tsx";
import * as $s_slug_ from "./routes/s/[slug].tsx";
import * as $signup from "./routes/signup.tsx";
import * as $spaces_id_edit from "./routes/spaces/[id]/edit.tsx";
import * as $spaces_new from "./routes/spaces/new.tsx";
import * as $subscribe from "./routes/subscribe.tsx";
import * as $units_id_ from "./routes/units/[id].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CouponForm from "./islands/CouponForm.tsx";
import * as $ProgressButton from "./islands/ProgressButton.tsx";
import * as $ReferralCode from "./islands/ReferralCode.tsx";
import * as $SpaceForm from "./islands/SpaceForm.tsx";
import * as $UnitNode from "./islands/UnitNode.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin.tsx": $admin,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/api/joke.ts": $api_joke,
    "./routes/billing.tsx": $billing,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/lp.tsx": $lp,
    "./routes/map/index.tsx": $map_index,
    "./routes/mentors/[slug].tsx": $mentors_slug_,
    "./routes/mentors/index.tsx": $mentors_index,
    "./routes/profile/edit.tsx": $profile_edit,
    "./routes/s/[slug].tsx": $s_slug_,
    "./routes/signup.tsx": $signup,
    "./routes/spaces/[id]/edit.tsx": $spaces_id_edit,
    "./routes/spaces/new.tsx": $spaces_new,
    "./routes/subscribe.tsx": $subscribe,
    "./routes/units/[id].tsx": $units_id_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/CouponForm.tsx": $CouponForm,
    "./islands/ProgressButton.tsx": $ProgressButton,
    "./islands/ReferralCode.tsx": $ReferralCode,
    "./islands/SpaceForm.tsx": $SpaceForm,
    "./islands/UnitNode.tsx": $UnitNode,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
